import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { PublicLayout } from "../../components/layouts/public-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <PublicLayout>{children}</PublicLayout>;
}
