export const NEXT_PUBLIC_SENDGRID_API_KEY =
  (process.env.NEXT_PUBLIC_SENDGRID_API_KEY as string) || "";

export const NEXT_PUBLIC_EMAIL_VERIFICATION_REDIRECT_URL =
  process.env.NEXT_PUBLIC_EMAIL_VERIFICATION_REDIRECT_URL || "";

export const NEXT_PUBLIC_TRACECORK_EMAIL =
  process.env.NEXT_PUBLIC_TRACECORK_EMAIL || "";

export const NEXT_PUBLIC_CAPTCHA_SITE_KEY =
  process.env.NEXT_PUBLIC_CAPTCHA_SITE_KEY || "";
